<a href="https://colab.research.google.com/github/RaulOrtiz2000/ml_2023/blob/main/Ejercicio6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [26]:
mainpath = 'CSVS'
filename = 'Social_Network_Ads.csv'
fullpath = os.path.join(mainpath,filename)

In [27]:
dataset = pd.read_csv(fullpath)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,
random_state = 6)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[    46  32000]
 [    37  70000]
 [    50  20000]
 [    38  71000]
 [    30  89000]
 [    47  30000]
 [    48  29000]
 [    38  61000]
 [    53 143000]
 [    20  23000]
 [    49  89000]
 [    27  58000]
 [    34 115000]
 [    35  60000]
 [    34  43000]
 [    42  70000]
 [    28  84000]
 [    27  88000]
 [    31  68000]
 [    20  82000]
 [    24  58000]
 [    59  88000]
 [    37  78000]
 [    41  72000]
 [    28  55000]
 [    35  88000]
 [    24  32000]
 [    39  42000]
 [    48  41000]
 [    37  57000]
 [    21  72000]
 [    49 141000]
 [    32  18000]
 [    40  60000]
 [    42 104000]
 [    57  74000]
 [    26  30000]
 [    31  76000]
 [    55  39000]
 [    48  35000]
 [    40 107000]
 [    38  59000]
 [    52 114000]
 [    27  58000]
 [    44 139000]
 [    33  43000]
 [    37 137000]
 [    55 125000]
 [    28  87000]
 [    19  19000]
 [    26  15000]
 [    37  75000]
 [    23  63000]
 [    30  79000]
 [    49  28000]
 [    40  59000]
 [    29  83000]
 [    33  31000]
 [    35  2500

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 0.79894738 -1.13273502]
 [-0.04899206  0.03145351]
 [ 1.17580935 -1.50037351]
 [ 0.04522344  0.06209006]
 [-0.7085005   0.61354778]
 [ 0.89316287 -1.1940081 ]
 [ 0.98737836 -1.22464464]
 [ 0.04522344 -0.24427535]
 [ 1.45845582  2.26792097]
 [-1.65065543 -1.40846389]
 [ 1.08159385  0.61354778]
 [-0.99114698 -0.33618497]
 [-0.33163853  1.41009784]
 [-0.23742304 -0.27491189]
 [-0.33163853 -0.79573308]
 [ 0.42208541  0.03145351]
 [-0.89693149  0.46036508]
 [-0.99114698  0.58291124]
 [-0.61428501 -0.02981957]
 [-1.65065543  0.399092  ]
 [-1.27379346 -0.33618497]
 [ 2.02374878  0.58291124]
 [-0.04899206  0.27654584]
 [ 0.32786991  0.0927266 ]
 [-0.89693149 -0.42809459]
 [-0.23742304  0.58291124]
 [-1.27379346 -1.13273502]
 [ 0.13943893 -0.82636962]
 [ 0.98737836 -0.85700616]
 [-0.04899206 -0.36682151]
 [-1.55643994  0.0927266 ]
 [ 1.08159385  2.20664789]
 [-0.52006952 -1.56164659]
 [ 0.23365442 -0.27491189]
 [ 0.42208541  1.07309589]
 [ 1.83531779  0.15399968]
 [-1.08536247 -1.1940081 ]
 

In [30]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [31]:
print(classifier.predict(sc.transform([[38,87000]])))

[0]


In [32]:
y_pred = classifier.predict(X_test)

np.set_printoptions(precision=2)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
